---
title: About Us
output: 
  html_document:
    toc: true
    toc_float: true
---

### Tasya Dita 
[Tasya Dita](https://tpd2121.github.io/tpd2121_hw4.github.io/) is currently on her 2nd year of MPH at Mailman School of Public Health, under the Population & Family Health department, with interest in maternal health and health promotion. 

### Zihan Lin 

[Zihan Lin](https://zzihanlin.github.io/) is curently a 1st year MS Biostatistics student at Columbia University Mailman School of Public Health, concentrating in Public Health Data Science track.


### Adeena Moghni 

[Adeena Moghni](https://adeenamoghni.github.io/) is currently an MS Biostatistics student at Columbia University Mailman School of Public Health, concentrating in Statistical Genetics

### Kimberly Palaguachi-Lopez 

[Kimberly Palaguachi-Lopez](https://klopez67.github.io/about.html) is currently a graduate student pursuing her Masters of Science in Biostatistics on the Health Data Science track at Columbia University Mailman School of Public Health.



### Hanchuan Chen

[Hanchuan Chen](https://documentdog.github.io/) is currently an MS Biostatistics student at Columbia University Mailman School of Public Health, Theory and Method track.





