---
title: "Untitled"
author: "Adeena Moghni"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rnoaa)
```

##Weather data

```{r tidying rnoaa data}
state_codes = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")

year = 2011:2021

state_stations = ghcnd_stations() %>% 
  filter(state %in% state_codes) %>% 
  select(id, state) %>% 
  group_by(state) %>% 
  sample_n(30) %>% 
  ungroup()
```

```{r function rnoaa}
temp_func <- function(monitor_id, state) {
 
  avg_temp <- meteo_pull_monitors(
    monitors = monitor_id,
    var = c("TMAX", "TMIN"),
    date_min = "2011-01-01",
    date_max = "2021-12-31"
  )
  
  if ("tmin" %in% colnames(avg_temp) && "tmax" %in% colnames(avg_temp)) {
    
    avg_temp <- avg_temp %>%
      mutate(
        state = state, 
        tmin = tmin / 10,  
        tmax = tmax / 10,  
        tavg_daily = (tmin + tmax) / 2,  
        date = as.character(date)
      ) %>%
      separate(date, into = c("year", "month", "day"), sep = "-") %>%
      mutate(
        across(c(year, month, day), as.numeric),  
        season = case_when(
          month %in% c(12, 1, 2) ~ "Winter",
          month %in% c(3, 4, 5) ~ "Spring",
          month %in% c(6, 7, 8) ~ "Summer",
          month %in% c(9, 10, 11) ~ "Fall"
        )
      ) %>%
      drop_na()  
    
    return(avg_temp)
  } else {
    return(NULL)
  }
}
```

```{r}
library(furrr)

plan(multisession, workers = parallel::detectCores() - 1)

temp_data_list = 
  future_map2(state_stations$id, 
              state_stations$state, 
              temp_func, 
              .options = furrr_options(seed = TRUE))
```

```{r}
seasonal_avg_temps = bind_rows(temp_data_list) %>% 
  group_by(state, year, season) %>% 
  summarize(avg_temp = mean(tavg_daily, na.rm = TRUE))

write.csv(seasonal_avg_temps, "temp_data.csv", row.names = FALSE)
```

## Asthma data
```{r asthma dataset}
library(rvest)
library(httr)

#write the data loading steps
asthma_2011 = read_html("https://www.cdc.gov/asthma/brfss/2011/tableC1.htm") %>% 
  html_table() %>% 
  bind_rows() %>% 
  janitor::clean_names() %>% 
  select(-x) %>% 
  filter(!state %in% c("U.S. Total**", "Territories", "PR")) %>% 
  mutate(year = "2011")

#i use current asthma prevalence (table c1) rather than lifetime prevalence and only keep the prevalence percent (instead of numbers) 
#i am excluding PR, VI, and GU

#write the functions for data loading

asthma_hmtl = function(url) {
  
  df = 
    read_html(url) %>% 
    html_table() %>% 
    bind_rows() %>% 
    janitor::clean_names() %>% 
    select(state, prevalence_percent) %>% 
    filter(!state %in% c("U.S. Total**", "U.S. Totalf", "Territories", "PR", "GU", "VI")) %>% 
    mutate(prevalence_percent = as.numeric(prevalence_percent))
}

asthma_dataset = 
  tibble(
    year_name = 2011:2021,
    data_url = c(
    "https://www.cdc.gov/asthma/brfss/2011/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2012/tableC1.htm", 
    "https://www.cdc.gov/asthma/brfss/2013/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2014/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2015/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2016/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2017/tableC1.htm",
    "https://www.cdc.gov/asthma/brfss/2018/tableC1.html",
    "https://www.cdc.gov/asthma/brfss/2019/tableC1.html",
    "https://www.cdc.gov/asthma/brfss/2020/tableC1.html",
    "https://www.cdc.gov/asthma/brfss/2021/tableC1.html")
  ) %>% 
  mutate(asthma_byyear = map(data_url, asthma_hmtl)) %>% 
  unnest(asthma_byyear) %>% 
  select(-data_url) %>% 
  group_by(year_name)

#starting from 2016, has column called "weighted_number" instead of prevalence number
#2016 and 2021 includes VI (removed)
#2020 and 2021 has U.S. totalf (removed)
#2019 and 2021 only has 49 states (-NJ and -FL)

library(plotly)

asthma_dataset %>% 
  plot_ly(x = ~year_name, y = ~prevalence_percent, color = ~state, type = "box", colors = "viridis")

plot_ly(asthma_dataset, x = ~year_name, y = ~prevalence_percent, color = ~state, type = "scatter", showlegend = FALSE)

asthma_dataset %>% 
  mutate(year_name = as.factor(year_name)) %>% 
  ggplot(aes(x = year_name, y = prevalence_percent)) + 
  geom_boxplot(aes(fill = year_name), color = "blue", alpha = .5) + 
  labs(
    x = "Year",
    y = "Prevalence_percent",
    title = "Asthma cases by year"
  ) +
  theme_minimal()

asthma_dataset %>% 
  ggplot(aes(x = state, y = prevalence_percent)) + 
  geom_boxplot() + 
  labs(
    x = "State",
    y = "Prevalence_percent",
    title = "Asthma cases by state"
  ) +
  theme_minimal()


```

## fit linear regression
```{r}
# 1. merge asthma prevalance and temp data 
temp_df = read_csv("./temp_data.csv")
summary(temp_df)
# 2. do EDA and check distribution assumption
temp_df |> 
  ggplot(aes(x = avg_temp)) +
  geom_histogram() +
  labs(
    title = "distribution of average temperature in 2011-2021",
    xlab = "average temperature",
    ylab = "frequency"
  )
# 3. do linear regression

# 4. results explanation and visualization
```

