---
title: "mapping"
author: "Kimberly Lopez"
date: "2024-12-03"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tigris)
library(sf)
library(usmap) # May need to install.packages to run this 
library(ggplot2)
library(dplyr)
```


Downloading state shape file Data 
Merging Asthma & temp & shapefile data 

```{r}
shape_files = usmap::us_map()

asthma_df = read_csv("data/asthma_data.csv")
weather_df = read_csv("data/temp_data.csv")

merged_data=  
  shape_files|> 
  left_join(asthma_df, by = c("abbr" = "state")) |>
  mutate(state= abbr)

annual_weather =
  weather_df|>
  group_by(state, year) |>
  summarize(avg_temp_annual = mean(avg_temp, na.rm = TRUE), .groups = "drop")


asthma_weather= 
  asthma_df |>
  left_join(weather_df, by = c("state"))|>
  select(-year_name)

final_df=
  shape_files |>
  mutate(state= abbr)|>
  left_join(asthma_weather, by = "state")
```


Mapping Prevalence data by state: 

```{r}
final_df|> 
  filter(year==2011)|>
  ggplot() +
  geom_sf(aes(fill = prevalence_percent), color = "white") +
  scale_fill_viridis_c(na.value = "grey90") + 
  theme_minimal() +
  labs(
    title = "Asthma Prevalence by State (2011)",
    fill = "Prevalence (%)"
  ) +
  theme(
    panel.grid = element_blank(), 
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )

final_df|> 
  filter(year==2012)|>
  ggplot() +
  geom_sf(aes(fill = prevalence_percent), color = "white") +
  scale_fill_viridis_c(na.value = "grey90") + 
  theme_minimal() +
  labs(
    title = "Asthma Prevalence by State (2012)",
    fill = "Prevalence (%)"
  ) +
  theme(
    panel.grid = element_blank(), 
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )

final_df|> 
  filter(year==2013)|>
  ggplot() +
  geom_sf(aes(fill = prevalence_percent), color = "white") +
  scale_fill_viridis_c(na.value = "grey90") + 
  theme_minimal() +
  labs(
    title = "Asthma Prevalence by State (2013)",
    fill = "Prevalence (%)"
  ) +
  theme(
    panel.grid = element_blank(), 
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )


```

