<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Zihan Lin" />


<title>Report</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Data Import
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="temp_function.html">Temperature Data</a>
    </li>
    <li>
      <a href="asthma_function.html">Asthma Data</a>
    </li>
  </ul>
</li>
<li>
  <a href="regression.html">Regression Analysis</a>
</li>
<li>
  <a href="mapping.html">Data Visualization/ EDA</a>
</li>
<li>
  <a href="https://klopez67.shinyapps.io/final_draft/">Shiny</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-envelope fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:&lt;hc3563@cumc.columbia.edu&gt;">Hanchuan Chen</a>
    </li>
    <li>
      <a href="mailto:&lt;tpd2121@cumc.columbia.edu&gt;">Tasya Dita</a>
    </li>
    <li>
      <a href="mailto:&lt;zl3543@cumc.columbia.edu&gt;">Zihan Lin</a>
    </li>
    <li>
      <a href="mailto:&lt;am6592@cumc.columbia.edu&gt;">Adeena Moghni</a>
    </li>
    <li>
      <a href="mailto:&lt;kp2809@cumc.columbia.edu&gt;">Kimberly Palaguachi-Lopez</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/zzihanlin/p8105_final_project.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Report</h1>
<h4 class="author">Zihan Lin</h4>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Extreme weather is on the rise due to climate change, with many,
especially those who come from a lower socioeconomic background, already
feeling the adverse effects changing weather patterns. Asthma is a
co-morbidity for other chronic diseases and also disproportionately
affects those from a lower economic status. In this project, we want to
focus on asthma prevalence/incidence as hotter temperatures can lead to
more pollen, air pollution, and other lung irritants. Studying these
trends will help understand the health risks in vulnerable
populations.</p>
<p>Key Questions:<br />
1. How do asthma cases correlate with temperature extremes?<br />
2. Are there temporal or spatial patterns in asthma prevalence?</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>To retrieve the temperature data, different options were explored
from within the rnoaa package. meteo_pull_monitors() was first explored,
but due to the number of monitors from each state, it was not realistic
to pull data from each monitor to calculate the average temperature over
a 10-year period. ncdc() was then investigated for use. This uses the
National Climatic Data Center to access weather data and already has a
TAVG variable for the average temperature. However, there were
limitations as it could only gather data one year at a time and there
was also issues with the API of this site. Using online resources was
not realistic as datasets online were typically separated by
year/month/day so getting a seasonal average was not possible. In the
end, the temperature data was extracted using meteo_pull_monitors(). 30
monitors from each state were randomly selected and the daily mean of
each station was found by averaging the minimum and maximum temperatures
(the TAVG as reported by meteo_pull_monitors() could not be used as many
stations were missing this data) for every day from 1/1/2011 to
12/31/2021 in every state. The data was then grouped by state, year, and
season to find the seasonal average for every state in every year.</p>
<p>The analysis uses two primary datasets: Asthma Data and Temperature
Data.</p>
<pre class="r"><code># Load datasets
asthma_data &lt;- read_csv(&quot;data/asthma_data.csv&quot;)</code></pre>
<pre><code>## Rows: 559 Columns: 3
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): state
## dbl (2): year_name, prevalence_percent
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>The Asthma Data consists of 559 observations and 3 variables, which
include details such as the date of record, the region, and the number
of asthma cases reported (cases). A brief look at the first few rows
reveals the following column names: year_name, state,
prevalence_percent, NA, NA, providing an overview of the key information
captured.</p>
<pre class="r"><code>temp_data &lt;- read_csv(&quot;data/temp_data.csv&quot;)</code></pre>
<pre><code>## Rows: 2193 Columns: 4
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): state, season
## dbl (2): year, avg_temp
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>The Temperature Data contains 2193 observations and 4 variables, with
key columns including the date of the temperature reading (date), the
region (region), and the recorded temperature (temp). This dataset
provides critical environmental context for analyzing the relationship
between temperature and asthma cases.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<pre class="r"><code># Summary of asthma data
asthma_summary &lt;- asthma_data %&gt;%
  summarize(
    avg_prevalence = mean(prevalence_percent, na.rm = TRUE),
    min_prevalence = min(prevalence_percent, na.rm = TRUE),
    max_prevalence = max(prevalence_percent, na.rm = TRUE)
  )

# Create a tidy table for asthma summary using kable
asthma_summary %&gt;%
  knitr::kable(
    col.names = c(&quot;Average Prevalence (%)&quot;, &quot;Minimum Prevalence (%)&quot;, &quot;Maximum Prevalence (%)&quot;),
    caption = &quot;Summary Statistics for Asthma Prevalence&quot;
  )</code></pre>
<table>
<caption>Summary Statistics for Asthma Prevalence</caption>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Average Prevalence (%)</th>
<th align="right">Minimum Prevalence (%)</th>
<th align="right">Maximum Prevalence (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">9.422719</td>
<td align="right">6.2</td>
<td align="right">13.2</td>
</tr>
</tbody>
</table>
<p>The average prevalence of asthma across the dataset is approximately
9.42%. The minimum prevalence is 6.2%, while the maximum prevalence is
13.2%. This range suggests notable variability in asthma prevalence
across regions or time periods.</p>
<pre class="r"><code># Summary of temperature data
temp_summary &lt;- temp_data %&gt;%
  summarize(
    avg_temp_overall = mean(avg_temp, na.rm = TRUE),
    min_temp = min(avg_temp, na.rm = TRUE),
    max_temp = max(avg_temp, na.rm = TRUE)
  )

# Create a tidy table for temperature summary
temp_summary %&gt;%
  knitr::kable(
    col.names = c(&quot;Average Temperature (°C)&quot;, &quot;Minimum Temperature (°C)&quot;, &quot;Maximum Temperature (°C)&quot;),
    caption = &quot;Summary Statistics for Temperature Data&quot;
  )</code></pre>
<table>
<caption>Summary Statistics for Temperature Data</caption>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Average Temperature (°C)</th>
<th align="right">Minimum Temperature (°C)</th>
<th align="right">Maximum Temperature (°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">11.87722</td>
<td align="right">-14.00078</td>
<td align="right">30.258</td>
</tr>
</tbody>
</table>
<pre class="r"><code>temp_summary</code></pre>
<pre><code>## # A tibble: 1 × 3
##   avg_temp_overall min_temp max_temp
##              &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1             11.9    -14.0     30.3</code></pre>
<p>The overall average temperature is approximately 11.88°C, with a wide
range from -14.0°C (minimum) to 30.26°C (maximum). The large temperature
range indicates that the dataset spans multiple regions with diverse
climates.</p>
<pre class="r"><code># Average temperature by year
yearly_temp_summary &lt;- temp_data %&gt;%
  group_by(year) %&gt;%
  summarize(
    avg_temp = mean(avg_temp, na.rm = TRUE)
  )

# Create a tidy table for yearly temperature summary
yearly_temp_summary %&gt;%
  knitr::kable(
    col.names = c(&quot;Year&quot;, &quot;Average Temperature (°C)&quot;),
    caption = &quot;Average Temperature by Year&quot;
  )</code></pre>
<table>
<caption>Average Temperature by Year</caption>
<thead>
<tr class="header">
<th align="right">Year</th>
<th align="right">Average Temperature (°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2011</td>
<td align="right">11.66251</td>
</tr>
<tr class="even">
<td align="right">2012</td>
<td align="right">12.65061</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">11.12633</td>
</tr>
<tr class="even">
<td align="right">2014</td>
<td align="right">10.94758</td>
</tr>
<tr class="odd">
<td align="right">2015</td>
<td align="right">12.05795</td>
</tr>
<tr class="even">
<td align="right">2016</td>
<td align="right">12.56135</td>
</tr>
<tr class="odd">
<td align="right">2017</td>
<td align="right">12.20775</td>
</tr>
<tr class="even">
<td align="right">2018</td>
<td align="right">11.68774</td>
</tr>
<tr class="odd">
<td align="right">2019</td>
<td align="right">11.39799</td>
</tr>
<tr class="even">
<td align="right">2020</td>
<td align="right">12.12918</td>
</tr>
<tr class="odd">
<td align="right">2021</td>
<td align="right">12.23760</td>
</tr>
</tbody>
</table>
<pre class="r"><code>yearly_temp_summary</code></pre>
<pre><code>## # A tibble: 11 × 2
##     year avg_temp
##    &lt;dbl&gt;    &lt;dbl&gt;
##  1  2011     11.7
##  2  2012     12.7
##  3  2013     11.1
##  4  2014     10.9
##  5  2015     12.1
##  6  2016     12.6
##  7  2017     12.2
##  8  2018     11.7
##  9  2019     11.4
## 10  2020     12.1
## 11  2021     12.2</code></pre>
<pre class="r"><code>ggplot(yearly_temp_summary, aes(x = year, y = avg_temp)) +
  geom_line(color = &quot;blue&quot;) +
  labs(
    title = &quot;Average Temperature Over Time&quot;,
    x = &quot;Year&quot;,
    y = &quot;Average Temperature (°C)&quot;
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The line plot shows annual average temperatures over the years. There
are visible fluctuations, with some years showing higher average
temperatures (e.g., 2012) and others lower (e.g., 2014). The average
temperature peaked around 2012 and dipped notably around 2013-2014.
There is no clear upward or downward trend in the dataset; instead,
temperatures appear cyclical or influenced by short-term climate
variations.</p>
<pre class="r"><code># Average temperature by season
seasonal_temp_summary &lt;- temp_data %&gt;%
  group_by(season) %&gt;%
  summarize(
    avg_temp = mean(avg_temp, na.rm = TRUE)
  )

# Create a tidy table for seasonal temperature summary
seasonal_temp_summary %&gt;%
  knitr::kable(
    col.names = c(&quot;Season&quot;, &quot;Average Temperature (°C)&quot;),
    caption = &quot;Average Temperature by Season&quot;
  )</code></pre>
<table>
<caption>Average Temperature by Season</caption>
<thead>
<tr class="header">
<th align="left">Season</th>
<th align="right">Average Temperature (°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fall</td>
<td align="right">12.850739</td>
</tr>
<tr class="even">
<td align="left">Spring</td>
<td align="right">11.056397</td>
</tr>
<tr class="odd">
<td align="left">Summer</td>
<td align="right">22.445812</td>
</tr>
<tr class="even">
<td align="left">Winter</td>
<td align="right">1.175468</td>
</tr>
</tbody>
</table>
<pre class="r"><code>seasonal_temp_summary</code></pre>
<pre><code>## # A tibble: 4 × 2
##   season avg_temp
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Fall      12.9 
## 2 Spring    11.1 
## 3 Summer    22.4 
## 4 Winter     1.18</code></pre>
<pre class="r"><code>ggplot(seasonal_temp_summary, aes(x = season, y = avg_temp, fill = season)) +
  geom_bar(stat = &quot;identity&quot;) +
  labs(
    title = &quot;Average Temperature by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Temperature (°C)&quot;
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The bar plot displays the average temperature for each season. Summer
is significantly warmer (22.45°C on average), while Winter is coldest
(1.18°C on average). Fall and Spring fall in between. The seasonal
temperature differences are as expected, with clear distinctions between
warmer and colder periods. The significant gap between Winter and Summer
highlights the need to examine whether asthma prevalence increases
during colder months due to weather-induced triggers.</p>
<pre class="r"><code># Temperature by state
state_temp_summary &lt;- temp_data %&gt;%
  group_by(state) %&gt;%
  summarize(
    avg_temp = mean(avg_temp, na.rm = TRUE)
  )

ggplot(state_temp_summary, aes(x = reorder(state, -avg_temp), y = avg_temp)) +
  geom_bar(stat = &quot;identity&quot;, fill = &quot;steelblue&quot;) +
  coord_flip() +
  labs(
    title = &quot;Average Temperature by State&quot;,
    x = &quot;State&quot;,
    y = &quot;Average Temperature (°C)&quot;
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The horizontal bar plot ranks states by their average temperature.
States on the left (e.g., colder climates) have lower average
temperatures, while those on the right (e.g., warmer climates) have
higher averages. There is substantial geographic variation in average
temperatures across states. States like Alaska are likely on the colder
end, while southern states such as Florida or Texas may be on the warmer
end.</p>
<pre class="r"><code># Merge datasets by year and state
merged_data &lt;- inner_join(
  asthma_data,
  temp_data,
  by = c(&quot;year_name&quot; = &quot;year&quot;, &quot;state&quot; = &quot;state&quot;)
)

# Display first few rows of merged data
head(merged_data)</code></pre>
<pre><code>## # A tibble: 6 × 5
##   year_name state prevalence_percent season avg_temp
##       &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
## 1      2011 AL                   8   Fall      17.0 
## 2      2011 AL                   8   Spring    17.9 
## 3      2011 AL                   8   Summer    27.2 
## 4      2011 AL                   8   Winter     7.25
## 5      2011 AK                   8.2 Fall       1.83
## 6      2011 AK                   8.2 Spring     2.12</code></pre>
<p>The merged dataset includes columns for year_name, state,
prevalence_percent, season, and avg_temp. Each row represents data for a
specific state, year, and season, showing asthma prevalence percentages
and average temperature.</p>
<pre class="r"><code># Calculate correlation
correlation &lt;- cor(
  merged_data$prevalence_percent,
  merged_data$avg_temp,
  use = &quot;complete.obs&quot;
)

cat(&quot;The correlation between asthma prevalence and temperature is:&quot;, correlation)</code></pre>
<pre><code>## The correlation between asthma prevalence and temperature is: -0.1330356</code></pre>
<p>The correlation between asthma prevalence and temperature is
-0.1330356. A correlation of -0.13 suggests a weak negative relationship
between temperature and asthma prevalence. This implies that as
temperatures increase, asthma prevalence slightly decreases, but the
relationship is not strong. This weak correlation indicates that other
factors may play more significant roles in asthma prevalence.</p>
<pre class="r"><code># Scatter plot with regression line
ggplot(merged_data, aes(x = avg_temp, y = prevalence_percent)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = &quot;lm&quot;, se = FALSE, color = &quot;blue&quot;) +
  labs(
    title = &quot;Asthma Prevalence vs Temperature&quot;,
    x = &quot;Average Temperature (°C)&quot;,
    y = &quot;Asthma Prevalence (%)&quot;
  )</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The scatter plot visualizes the relationship between average
temperature (x-axis) and asthma prevalence (y-axis). A regression line
is overlaid, showing a slight downward slope, consistent with the weak
negative correlation. The data points are widely scattered, confirming
that temperature alone does not strongly predict asthma prevalence. The
slight downward slope of the regression line reflects the weak negative
correlation.</p>
<p>Clusters of points around specific temperature ranges (e.g.,
~10–20°C) suggest that more observations are concentrated in these
moderate temperatures. Warmer temperatures might reduce asthma triggers
like cold air exposure, leading to slightly lower prevalence. Other
seasonal factors (e.g., pollen in Spring or high humidity in Summer)
could interact with temperature and affect asthma prevalence.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
