---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)
library(p8105.datasets)
library(shiny)
library(tidyverse)
library(tigris)
library(sf)
library(usmap) # May need to install.packages to run this 
library(ggplot2)
library(dplyr)
library(forecast)
```

```{r}
shape_files = usmap::us_map()
asthma_df = read_csv("data/asthma_data.csv")|>
  mutate(year= year_name)
weather_df = read_csv("data/temp_data.csv")

asthma_weather = 
  asthma_df |>
  left_join(weather_df, by = c("state", "year")) 

final_df =
  shape_files |>
  mutate(state = abbr) |>                           
  left_join(asthma_weather, by = "state") |>        
  drop_na() 
```





Column {.sidebar}
-----------------------------------------------------------------------

```{r}
state_choices = 
  final_df|>
  st_drop_geometry()|>
  select(full) |> 
  distinct()|>
  pull()
 
selectInput(
  inputId = "state_choice", 
  label = h3(" Select State"),
  choices = state_choices, 
  selected = "AL"
)
```

```{r}
year_choice = 
  final_df|>
  st_drop_geometry()|>
  select(year) |> 
  distinct()|>
  pull()

selectInput(
  inputId = "year_choice", 
  label = h3(" Select Year"),
  choices = year_choice, 
  selected = "year"
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Asthma Prevalance (%) in the US

```{r}

renderPlotly( 
  final_df|> 
    filter( year == input[["year_choice"]])|> 
    ggplot() +
    geom_sf(aes(fill = prevalence_percent), color = "white") +
    scale_fill_viridis_c(na.value = "grey90") + theme_minimal() +
    labs(
          title = paste("Asthma Prevalence (", input$year_choice, ")", sep = ""),
          fill = "Prevalence (%)") +
    theme(
        panel.grid = element_blank(), 
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### State Level Asthma Prevalance Data

```{r}

renderPlotly( 
  final_df|> 
    filter(
    full == input[["state_choice"]])|> 
    ggplot( aes(x = year, y = prevalence_percent, group = full)) +
    geom_line() +
    geom_point() +
    labs(
      title = paste(" ", input$state_choice),
      x = "Year",
      y = "Asthma Prevalence (%)"
    ) +
    scale_x_continuous(breaks = seq(min(final_df$year), max(final_df$year), by = 1)) +
    theme_minimal() + 
    theme(
      panel.grid = element_blank(),
      axis.text = element_text(angle = 45, hjust = 1)  
    ))
```

### State Level Temperature (C) Data

```{r}

renderPlot(final_df |> 
  filter(full == input[["state_choice"]]) |> 
  ggplot(aes(x = avg_temp, y = as.factor(year_name))) + 
  geom_density_ridges() +
  labs(
    title = "Density of Average Temperature Across Years",
    x = "Average Temperature",
    y = "Year") +
  theme_minimal()
)
```

